# Generated by Django 4.2.21 on 2025-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Event", "0002_event_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="repeat_weekdays",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
