version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT:-8001}:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend/eventHandler
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - ./frontend/eventHandler:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
